[package]
name = "zou"
description = "Supabase compatible backend on object storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
zou-pg = { path = "../zou-pg" }
zou-store = { path = "../zou-store" }
env_logger = { workspace = true }
log = { workspace = true }

[target.'cfg(unix)'.dependencies]
getrandom = { workspace = true }
libc = { workspace = true }
zou-server = { path = "../zou-server" }

[lints]
workspace = true
