[package]
name = "zou"
description = "Supabase compatible backend on object storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
zou-pg = { path = "../zou-pg" }
zou-store = { path = "../zou-store" }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[lints]
workspace = true
