//! The scoreboard: every number a run produced, in one file somebody
//! can read without running anything.
//!
//! A run prints its own summary, but the summary is in a log that is
//! gone in ninety days and that nobody outside CI ever sees. The claim
//! this project makes is a compatibility claim, so the evidence for it
//! has to be somewhere a person can look at without permission, and
//! that means a file in the repository, regenerated on every merge.
//!
//! Two cuts through the same run. A feature says what somebody was
//! testing, which is how the suite is organised. An endpoint says what
//! the server had to implement, which is what you can act on: "PATCH on
//! a table is at 30%" names the next piece of work, and "upsert is at
//! 52%" does not.
//!
//! Nothing here is a timestamp or a run number. A scoreboard with the
//! time in it changes on every merge, so the commit that regenerates it
//! stops being a signal and the history stops being a record of the
//! numbers moving. This file changes when a number changes.

use std::collections::BTreeMap;

use serde::Deserialize;

/// What `check --json` wrote: one entry per suite it ran.
#[derive(Deserialize)]
pub struct Runs {
    pub suites: Vec<Run>,
}

#[derive(Deserialize)]
pub struct Run {
    pub suite: String,
    pub against: String,
    pub compared_with: String,
    pub passed: usize,
    pub total: usize,
    pub percent: usize,
    #[serde(default)]
    pub known: usize,
    #[serde(default)]
    pub features: Vec<Group>,
    #[serde(default)]
    pub endpoints: Vec<Group>,
}

#[derive(Deserialize)]
pub struct Group {
    #[serde(rename = "feature", alias = "endpoint")]
    pub name: String,
    pub passed: usize,
    pub total: usize,
    pub percent: usize,
}

/// Jest's shape, which vitest writes too, and which is what a client's
/// own run is read out of. Only the fields that end up on the scoreboard
/// are named here, so a reporter that grows a field does not break this.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Js {
    #[serde(default)]
    pub test_results: Vec<JsFile>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JsFile {
    #[serde(default)]
    pub assertion_results: Vec<JsTest>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JsTest {
    /// `passed`, `failed`, or `pending`, which is what vitest calls a
    /// skip.
    pub status: String,
    #[serde(default)]
    pub ancestor_titles: Vec<String>,
}

struct Block {
    name: String,
    passed: usize,
    failed: usize,
    skipped: usize,
}

/// The whole document. The js runs are named on the command line, one
/// per client whose own tests were pointed at zou.
pub fn render(runs: &[Run], js: &[(String, Js)], pin: Option<&str>) -> String {
    let mut out = String::new();
    out.push_str(
        "# Compatibility scoreboard\n\n\
         Generated by `zou-conformance scoreboard` and committed by CI on every merge to \
         main, so the numbers here are the numbers the last merge measured rather than the \
         numbers somebody last remembered to write down. There is no date in it: it changes \
         when a number changes.\n\n\
         A pass means zou answered what the reference answered, byte for byte or as the same \
         json written differently. A known difference is still counted as a failure here. It \
         is only excused from the exit code, so this scoreboard cannot be improved by writing \
         something down.\n\n",
    );
    if let Some(pin) = pin {
        out.push_str(&format!(
            "The questions and the recorded answers are \
             [tamnd/zou-conformance](https://github.com/tamnd/zou-conformance) at `{}`.\n\n",
            &pin[..pin.len().min(12)]
        ));
    }

    out.push_str("## Where it stands\n\n");
    out.push_str("| suite | compared with | passing | of | | known |\n");
    out.push_str("| --- | --- | ---: | ---: | ---: | ---: |\n");
    for run in runs {
        out.push_str(&format!(
            "| {} | {} | {} | {} | {}% | {} |\n",
            run.suite, run.compared_with, run.passed, run.total, run.percent, run.known
        ));
    }
    for (name, js) in js {
        let blocks = blocks(js);
        let passed: usize = blocks.iter().map(|b| b.passed).sum();
        let failed: usize = blocks.iter().map(|b| b.failed).sum();
        out.push_str(&format!(
            "| {} | its own integration tests | {} | {} | {}% | 0 |\n",
            name,
            passed,
            passed + failed,
            percent(passed, passed + failed)
        ));
    }
    out.push('\n');

    for run in runs {
        out.push_str(&format!("## {} against {}\n\n", run.suite, run.against));
        if !run.endpoints.is_empty() {
            out.push_str("Per endpoint, which is what the server had to implement.\n\n");
            out.push_str(&table("endpoint", &run.endpoints));
        }
        if !run.features.is_empty() {
            out.push_str("Per feature, which is how the suite is organised.\n\n");
            out.push_str(&table("feature", &run.features));
        }
    }

    for (name, js) in js {
        out.push_str(&format!("## {name}\n\n"));
        out.push_str(&format!(
            "{name}'s own tests, run against zou with the url changed and not one \
             assertion touched. A skipped test is one that needs something zou does not \
             serve on that url yet, Realtime or image transforms: they are skipped rather \
             than deleted so that the count keeps saying how much of the file is not \
             being asked.\n\n"
        ));
        out.push_str("| block | passing | of | skipped |\n");
        out.push_str("| --- | ---: | ---: | ---: |\n");
        for block in blocks(js) {
            out.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                block.name,
                block.passed,
                block.passed + block.failed,
                block.skipped
            ));
        }
        out.push('\n');
    }
    out
}

fn table(what: &str, groups: &[Group]) -> String {
    let mut out = format!("| {what} | passing | of | |\n| --- | ---: | ---: | ---: |\n");
    for group in groups {
        out.push_str(&format!(
            "| {} | {} | {} | {}% |\n",
            group.name, group.passed, group.total, group.percent
        ));
    }
    out.push('\n');
    out
}

/// One row per describe block, which is the coarsest grouping the file
/// has and the one that says what part of the client is being asked.
fn blocks(js: &Js) -> Vec<Block> {
    let mut blocks: BTreeMap<String, Block> = BTreeMap::new();
    for file in &js.test_results {
        for test in &file.assertion_results {
            let name = test
                .ancestor_titles
                .last()
                .cloned()
                .unwrap_or_else(|| "ungrouped".to_string());
            let block = blocks.entry(name.clone()).or_insert(Block {
                name,
                passed: 0,
                failed: 0,
                skipped: 0,
            });
            match test.status.as_str() {
                "passed" => block.passed += 1,
                "pending" | "skipped" | "todo" => block.skipped += 1,
                _ => block.failed += 1,
            }
        }
    }
    blocks.into_values().collect()
}

/// Rounded down, the same way the run rounds it, so that the two agree.
fn percent(passed: usize, total: usize) -> usize {
    match total {
        0 => 100,
        total => passed * 100 / total,
    }
}

/// A report json, or several, in the order they were named.
pub fn read(paths: &[String]) -> Result<Vec<Run>, String> {
    let mut runs = Vec::new();
    for path in paths {
        let text = std::fs::read_to_string(path).map_err(|e| format!("{path}: {e}"))?;
        let read: Runs = serde_json::from_str(&text).map_err(|e| format!("{path}: {e}"))?;
        runs.extend(read.suites);
    }
    Ok(runs)
}

pub fn read_js(path: &str) -> Result<Js, String> {
    let text = std::fs::read_to_string(path).map_err(|e| format!("{path}: {e}"))?;
    serde_json::from_str(&text).map_err(|e| format!("{path}: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn runs() -> Vec<Run> {
        vec![Run {
            suite: "rest".to_string(),
            against: "zou".to_string(),
            compared_with: "postgrest 14.15 (recorded)".to_string(),
            passed: 71,
            total: 82,
            percent: 86,
            known: 11,
            features: vec![Group {
                name: "select".to_string(),
                passed: 7,
                total: 8,
                percent: 87,
            }],
            endpoints: vec![Group {
                name: "GET /rest/v1/{table}".to_string(),
                passed: 30,
                total: 38,
                percent: 78,
            }],
        }]
    }

    #[test]
    fn the_scoreboard_carries_both_cuts_through_the_run() {
        let out = render(&runs(), &[], None);
        assert!(out.contains("| rest | postgrest 14.15 (recorded) | 71 | 82 | 86% | 11 |"));
        assert!(out.contains("| GET /rest/v1/{table} | 30 | 38 | 78% |"));
        assert!(out.contains("| select | 7 | 8 | 87% |"));
    }

    /// A scoreboard that changes on every merge is a commit nobody
    /// reads, so there is nothing in it that moves on its own.
    #[test]
    fn the_same_run_twice_is_the_same_file() {
        assert_eq!(render(&runs(), &[], None), render(&runs(), &[], None));
    }

    #[test]
    fn the_pin_says_which_questions_these_answers_are_to() {
        let out = render(
            &runs(),
            &[],
            Some("55194722663a1cdfcd9eca133fbed9df64d0294c"),
        );
        assert!(out.contains("`55194722663a`"));
    }

    fn js() -> Js {
        let text = r#"{
            "testResults": [{
                "assertionResults": [
                    {"status": "passed", "ancestorTitles": ["Supabase", "PostgREST"]},
                    {"status": "passed", "ancestorTitles": ["Supabase", "PostgREST"]},
                    {"status": "pending", "ancestorTitles": ["Supabase", "Realtime"]},
                    {"status": "failed", "ancestorTitles": ["Supabase", "PostgREST"]}
                ]
            }]
        }"#;
        serde_json::from_str(text).expect("parses")
    }

    /// A skipped test is neither a pass nor a failure, and it is not
    /// invisible either.
    #[test]
    fn a_skipped_client_test_is_counted_apart() {
        let out = render(&runs(), &[("supabase-js".to_string(), js())], None);
        assert!(out.contains("| PostgREST | 2 | 3 | 0 |"));
        assert!(out.contains("| Realtime | 0 | 0 | 1 |"));
        assert!(out.contains("| supabase-js | its own integration tests | 2 | 3 | 66% | 0 |"));
    }

    /// Two clients are two rows and two sections, and nothing about the
    /// first of them is written into the renderer.
    #[test]
    fn every_client_that_ran_gets_its_own_line() {
        let out = render(
            &runs(),
            &[
                ("supabase-js".to_string(), js()),
                ("storage-js".to_string(), js()),
            ],
            None,
        );
        assert!(out.contains("| storage-js | its own integration tests | 2 | 3 | 66% | 0 |"));
        assert!(out.contains("## supabase-js\n"));
        assert!(out.contains("## storage-js\n"));
    }

    #[test]
    fn nothing_asked_is_not_nothing_passing() {
        assert_eq!(percent(0, 0), 100);
        assert_eq!(percent(1, 3), 33);
    }
}
