//! The scoreboard: every number a run produced, in one file somebody
//! can read without running anything.
//!
//! A run prints its own summary, but the summary is in a log that is
//! gone in ninety days and that nobody outside CI ever sees. The claim
//! this project makes is a compatibility claim, so the evidence for it
//! has to be somewhere a person can look at without permission, and
//! that means a file in the repository, regenerated on every merge.
//!
//! Two cuts through the same run. A feature says what somebody was
//! testing, which is how the suite is organised. An endpoint says what
//! the server had to implement, which is what you can act on: "PATCH on
//! a table is at 30%" names the next piece of work, and "upsert is at
//! 52%" does not.
//!
//! Nothing here is a timestamp or a run number. A scoreboard with the
//! time in it changes on every merge, so the commit that regenerates it
//! stops being a signal and the history stops being a record of the
//! numbers moving. This file changes when a number changes.

use std::collections::BTreeMap;

use serde::Deserialize;

/// What `check --json` wrote: one entry per suite it ran.
#[derive(Deserialize)]
pub struct Runs {
    pub suites: Vec<Run>,
}

#[derive(Deserialize)]
pub struct Run {
    pub suite: String,
    pub against: String,
    pub compared_with: String,
    pub passed: usize,
    pub total: usize,
    pub percent: usize,
    #[serde(default)]
    pub known: usize,
    #[serde(default)]
    pub features: Vec<Group>,
    #[serde(default)]
    pub endpoints: Vec<Group>,
}

#[derive(Deserialize)]
pub struct Group {
    #[serde(rename = "feature", alias = "endpoint")]
    pub name: String,
    pub passed: usize,
    pub total: usize,
    pub percent: usize,
}

/// Jest's shape, which vitest writes too, and which is what a client's
/// own run is read out of. Only the fields that end up on the scoreboard
/// are named here, so a reporter that grows a field does not break this.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Js {
    #[serde(default)]
    pub test_results: Vec<JsFile>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JsFile {
    #[serde(default)]
    pub assertion_results: Vec<JsTest>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JsTest {
    /// `passed`, `failed`, or `pending`, which is what vitest calls a
    /// skip.
    pub status: String,
    #[serde(default)]
    pub ancestor_titles: Vec<String>,
}

struct Block {
    name: String,
    passed: usize,
    failed: usize,
    skipped: usize,
}

/// The whole document. The js runs are named on the command line, one
/// per client whose own tests were pointed at zou, and the `ours` runs
/// beside them are the suites this project wrote, which are a different
/// claim and are labelled as one.
pub fn render(
    runs: &[Run],
    js: &[(String, Js)],
    ours: &[(String, Js)],
    pin: Option<&str>,
) -> String {
    let mut out = String::new();
    out.push_str(
        "# Compatibility scoreboard\n\n\
         Generated by `zou-conformance scoreboard` and committed by CI on every merge to \
         main, so the numbers here are the numbers the last merge measured rather than the \
         numbers somebody last remembered to write down. There is no date in it: it changes \
         when a number changes.\n\n\
         A pass means zou answered what the reference answered, byte for byte or as the same \
         json written differently. A known difference is still counted as a failure here. It \
         is only excused from the exit code, so this scoreboard cannot be improved by writing \
         something down.\n\n",
    );
    if let Some(pin) = pin {
        out.push_str(&format!(
            "The questions and the recorded answers are \
             [tamnd/zou-conformance](https://github.com/tamnd/zou-conformance) at `{}`.\n\n",
            &pin[..pin.len().min(12)]
        ));
    }

    out.push_str("## Where it stands\n\n");
    out.push_str("| suite | compared with | passing | of | | known |\n");
    out.push_str("| --- | --- | ---: | ---: | ---: | ---: |\n");
    for run in runs {
        out.push_str(&format!(
            "| {} | {} | {} | {} | {}% | {} |\n",
            run.suite, run.compared_with, run.passed, run.total, run.percent, run.known
        ));
    }
    for (name, js) in js {
        out.push_str(&summary(name, "its own integration tests", js));
    }
    for (name, js) in ours {
        out.push_str(&summary(name, "supabase start, in the same run", js));
    }
    out.push('\n');

    for run in runs {
        out.push_str(&format!("## {} against {}\n\n", run.suite, run.against));
        if !run.endpoints.is_empty() {
            out.push_str("Per endpoint, which is what the server had to implement.\n\n");
            out.push_str(&table("endpoint", &run.endpoints));
        }
        if !run.features.is_empty() {
            out.push_str("Per feature, which is how the suite is organised.\n\n");
            out.push_str(&table("feature", &run.features));
        }
    }

    for (name, js) in js {
        out.push_str(&format!("## {name}\n\n"));
        out.push_str(&format!(
            "{name}'s own tests, run against zou with the url changed and not one \
             assertion touched. A skipped test is one upstream skips itself, or one that \
             needs something zou does not serve on that url yet: they are skipped rather \
             than deleted so that the count keeps saying how much of the file is not \
             being asked.\n\n"
        ));
        out.push_str(&table_of(js));
    }

    for (name, js) in ours {
        out.push_str(&format!("## {name}\n\n"));
        out.push_str(&format!(
            "The questions in `{name}` are this project's own, because there is nothing \
             upstream that asks them. What keeps them honest is the other leg: the same \
             file is run against a real `supabase start` in the diff job of the same CI \
             run, so an assertion the reference does not pass is this suite being wrong \
             rather than zou being wrong. The number below is the zou leg.\n\n"
        ));
        out.push_str(&table_of(js));
    }
    out
}

/// One line in the table at the top, for a run that is a file of tests
/// rather than a suite with a recording.
fn summary(name: &str, compared_with: &str, js: &Js) -> String {
    let blocks = blocks(js);
    let passed: usize = blocks.iter().map(|b| b.passed).sum();
    let failed: usize = blocks.iter().map(|b| b.failed).sum();
    format!(
        "| {} | {} | {} | {} | {}% | 0 |\n",
        name,
        compared_with,
        passed,
        passed + failed,
        percent(passed, passed + failed)
    )
}

/// The per block table, which is the same shape whoever wrote the file.
fn table_of(js: &Js) -> String {
    let mut out =
        String::from("| block | passing | of | skipped |\n| --- | ---: | ---: | ---: |\n");
    for block in blocks(js) {
        out.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            block.name,
            block.passed,
            block.passed + block.failed,
            block.skipped
        ));
    }
    out.push('\n');
    out
}

fn table(what: &str, groups: &[Group]) -> String {
    let mut out = format!("| {what} | passing | of | |\n| --- | ---: | ---: | ---: |\n");
    for group in groups {
        out.push_str(&format!(
            "| {} | {} | {} | {}% |\n",
            group.name, group.passed, group.total, group.percent
        ));
    }
    out.push('\n');
    out
}

/// One row per describe block, which is the coarsest grouping the file
/// has and the one that says what part of the client is being asked.
fn blocks(js: &Js) -> Vec<Block> {
    let mut blocks: BTreeMap<String, Block> = BTreeMap::new();
    for file in &js.test_results {
        for test in &file.assertion_results {
            let name = test
                .ancestor_titles
                .last()
                .cloned()
                .unwrap_or_else(|| "ungrouped".to_string());
            let block = blocks.entry(name.clone()).or_insert(Block {
                name,
                passed: 0,
                failed: 0,
                skipped: 0,
            });
            match test.status.as_str() {
                "passed" => block.passed += 1,
                "pending" | "skipped" | "todo" => block.skipped += 1,
                _ => block.failed += 1,
            }
        }
    }
    blocks.into_values().collect()
}

/// Rounded down, the same way the run rounds it, so that the two agree.
fn percent(passed: usize, total: usize) -> usize {
    match total {
        0 => 100,
        total => passed * 100 / total,
    }
}

/// The lines a person puts around the table on a hand written page to
/// say that the numbers inside it are not theirs to type.
///
/// Html comments, because they are markdown's only way of writing
/// something that is in the file and not on the page, and Github renders
/// the page rather than the file.
pub const BEGIN: &str =
    "<!-- the numbers below come from the run, zou-conformance scoreboard --compat writes them -->";
pub const END: &str = "<!-- end of the numbers from the run -->";

/// The two lines above the rows, written out rather than parsed, so that
/// a page whose table has grown a column is refused with a message
/// naming the shape rather than rewritten into something else.
const HEADER: &str = "| suite | passing | of | | what it is |";
const RULE: &str = "| --- | ---: | ---: | ---: | --- |";

/// One suite's count, whichever kind of run it came out of.
pub struct Count {
    pub suite: String,
    pub passed: usize,
    pub total: usize,
}

/// Every suite in a run, flattened, since a page that quotes numbers
/// does not care whether one came from a recording or from a client's
/// own test file.
pub fn counted(runs: &[Run], js: &[(String, Js)], ours: &[(String, Js)]) -> Vec<Count> {
    let mut out: Vec<Count> = runs
        .iter()
        .map(|run| Count {
            suite: run.suite.clone(),
            passed: run.passed,
            total: run.total,
        })
        .collect();
    for (name, js) in js.iter().chain(ours) {
        let blocks = blocks(js);
        let passed: usize = blocks.iter().map(|b| b.passed).sum();
        let failed: usize = blocks.iter().map(|b| b.failed).sum();
        out.push(Count {
            suite: name.clone(),
            passed,
            total: passed + failed,
        });
    }
    out
}

/// Rewrite the numbers in the marked table on a hand written page, and
/// leave every other byte of the file alone.
///
/// This exists because `docs/compatibility.md` said its numbers came
/// from the same run this scoreboard does while somebody was typing
/// them in by hand, and they had drifted by nine cases on one row and a
/// whole known difference on another. The prose on that page is worth
/// having and no generator can write it, so the answer is not to
/// generate the page, it is to take the four cells a run knows better
/// than a person out of the person's hands.
///
/// The suite name is the first cell rather than the description, so that
/// a row can be matched against a run by something that does not change
/// when somebody improves a sentence. The last cell is the person's and
/// comes back untouched.
///
/// A page and a run that disagree about which suites exist is an error
/// both ways round. Filling in what is there and quietly dropping the
/// rest is how a row for a suite that stopped running stays on the page
/// forever with the last numbers it ever had.
pub fn recount(page: &str, counts: &[Count]) -> Result<String, String> {
    let begin = page
        .find(BEGIN)
        .ok_or_else(|| format!("no marker line, put {BEGIN} on the line above the table"))?;
    let end = page[begin..]
        .find(END)
        .map(|at| at + begin)
        .ok_or_else(|| format!("a begin marker and no end, put {END} below the table"))?;

    let mut rows = Vec::new();
    let mut lines = page[begin + BEGIN.len()..end]
        .lines()
        .map(str::trim)
        .filter(|line| line.starts_with('|'));
    match (lines.next(), lines.next()) {
        (Some(HEADER), Some(RULE)) => {}
        _ => {
            return Err(format!(
                "the table between the markers has to start\n{HEADER}\n{RULE}"
            ));
        }
    }
    for line in lines {
        let cells: Vec<&str> = line.trim_matches('|').split('|').map(str::trim).collect();
        let [suite, _, _, _, note] = cells[..] else {
            return Err(format!(
                "{line}\nhas {} cells where the header has 5",
                cells.len()
            ));
        };
        rows.push((suite.to_string(), note.to_string()));
    }

    for count in counts {
        if !rows.iter().any(|(suite, _)| *suite == count.suite) {
            return Err(format!(
                "the run has a suite named {} and the table has no row for it, add one with {} in the first cell and what it is in the last",
                count.suite, count.suite
            ));
        }
    }
    let mut out = page[..begin + BEGIN.len()].to_string();
    out.push_str("\n\n");
    out.push_str(HEADER);
    out.push('\n');
    out.push_str(RULE);
    out.push('\n');
    for (suite, note) in &rows {
        let count = counts
            .iter()
            .find(|count| count.suite == *suite)
            .ok_or_else(|| {
                format!(
                    "the table has a row for {suite} and the run has no suite by that name, either a report went missing from the run or the row is left over from a suite that was renamed"
                )
            })?;
        out.push_str(&format!(
            "| {} | {} | {} | {}% | {} |\n",
            suite,
            count.passed,
            count.total,
            percent(count.passed, count.total),
            note
        ));
    }
    out.push('\n');
    out.push_str(&page[end..]);
    Ok(out)
}

/// A report json, or several, in the order they were named.
pub fn read(paths: &[String]) -> Result<Vec<Run>, String> {
    let mut runs = Vec::new();
    for path in paths {
        let text = std::fs::read_to_string(path).map_err(|e| format!("{path}: {e}"))?;
        let read: Runs = serde_json::from_str(&text).map_err(|e| format!("{path}: {e}"))?;
        runs.extend(read.suites);
    }
    Ok(runs)
}

pub fn read_js(path: &str) -> Result<Js, String> {
    let text = std::fs::read_to_string(path).map_err(|e| format!("{path}: {e}"))?;
    serde_json::from_str(&text).map_err(|e| format!("{path}: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn runs() -> Vec<Run> {
        vec![Run {
            suite: "rest".to_string(),
            against: "zou".to_string(),
            compared_with: "postgrest 14.15 (recorded)".to_string(),
            passed: 71,
            total: 82,
            percent: 86,
            known: 11,
            features: vec![Group {
                name: "select".to_string(),
                passed: 7,
                total: 8,
                percent: 87,
            }],
            endpoints: vec![Group {
                name: "GET /rest/v1/{table}".to_string(),
                passed: 30,
                total: 38,
                percent: 78,
            }],
        }]
    }

    #[test]
    fn the_scoreboard_carries_both_cuts_through_the_run() {
        let out = render(&runs(), &[], &[], None);
        assert!(out.contains("| rest | postgrest 14.15 (recorded) | 71 | 82 | 86% | 11 |"));
        assert!(out.contains("| GET /rest/v1/{table} | 30 | 38 | 78% |"));
        assert!(out.contains("| select | 7 | 8 | 87% |"));
    }

    /// A scoreboard that changes on every merge is a commit nobody
    /// reads, so there is nothing in it that moves on its own.
    #[test]
    fn the_same_run_twice_is_the_same_file() {
        assert_eq!(
            render(&runs(), &[], &[], None),
            render(&runs(), &[], &[], None)
        );
    }

    #[test]
    fn the_pin_says_which_questions_these_answers_are_to() {
        let out = render(
            &runs(),
            &[],
            &[],
            Some("55194722663a1cdfcd9eca133fbed9df64d0294c"),
        );
        assert!(out.contains("`55194722663a`"));
    }

    fn js() -> Js {
        let text = r#"{
            "testResults": [{
                "assertionResults": [
                    {"status": "passed", "ancestorTitles": ["Supabase", "PostgREST"]},
                    {"status": "passed", "ancestorTitles": ["Supabase", "PostgREST"]},
                    {"status": "pending", "ancestorTitles": ["Supabase", "Realtime"]},
                    {"status": "failed", "ancestorTitles": ["Supabase", "PostgREST"]}
                ]
            }]
        }"#;
        serde_json::from_str(text).expect("parses")
    }

    /// A skipped test is neither a pass nor a failure, and it is not
    /// invisible either.
    #[test]
    fn a_skipped_client_test_is_counted_apart() {
        let out = render(&runs(), &[("supabase-js".to_string(), js())], &[], None);
        assert!(out.contains("| PostgREST | 2 | 3 | 0 |"));
        assert!(out.contains("| Realtime | 0 | 0 | 1 |"));
        assert!(out.contains("| supabase-js | its own integration tests | 2 | 3 | 66% | 0 |"));
    }

    /// Two clients are two rows and two sections, and nothing about the
    /// first of them is written into the renderer.
    #[test]
    fn every_client_that_ran_gets_its_own_line() {
        let out = render(
            &runs(),
            &[
                ("supabase-js".to_string(), js()),
                ("storage-js".to_string(), js()),
            ],
            &[],
            None,
        );
        assert!(out.contains("| storage-js | its own integration tests | 2 | 3 | 66% | 0 |"));
        assert!(out.contains("## supabase-js\n"));
        assert!(out.contains("## storage-js\n"));
    }

    /// A suite this project wrote is a different claim from a client's
    /// own tests, so it says what it was compared with rather than
    /// borrowing the line above it.
    #[test]
    fn a_suite_of_ours_says_which_leg_the_number_is() {
        let out = render(
            &runs(),
            &[("supabase-js".to_string(), js())],
            &[("js-functions".to_string(), js())],
            None,
        );
        assert!(out.contains("| supabase-js | its own integration tests | 2 | 3 | 66% | 0 |"));
        assert!(
            out.contains("| js-functions | supabase start, in the same run | 2 | 3 | 66% | 0 |")
        );
        assert!(out.contains("## js-functions\n"));
        assert!(out.contains("the same file is run against a real `supabase start`"));
    }

    #[test]
    fn nothing_asked_is_not_nothing_passing() {
        assert_eq!(percent(0, 0), 100);
        assert_eq!(percent(1, 3), 33);
    }

    /// A page shaped like the one this is for: prose that matters above
    /// and below, and four cells in the middle that a person kept
    /// getting wrong.
    fn page(rows: &str) -> String {
        format!(
            "## Where it stands\n\n{BEGIN}\n\n{HEADER}\n{RULE}\n{rows}\n{END}\n\nA known difference still counts as a failure in every number above.\n"
        )
    }

    #[test]
    fn the_numbers_come_from_the_run_and_the_words_stay_the_person_s() {
        let out = recount(
            &page("| rest | 82 | 82 | 100% | the surface a project actually uses |"),
            &counted(&runs(), &[], &[]),
        )
        .expect("the row is the one the run has");
        assert!(out.contains("| rest | 71 | 82 | 86% | the surface a project actually uses |"));
        assert!(out.contains("## Where it stands"));
        assert!(out.contains("A known difference still counts as a failure"));
    }

    /// The whole point of a generated block is that running it twice
    /// changes nothing, or CI commits a file on every merge and the
    /// history stops meaning anything.
    #[test]
    fn a_page_already_right_comes_back_byte_for_byte() {
        let counts = counted(&runs(), &[("supabase-js".to_string(), js())], &[]);
        let once = recount(
            &page("| rest | 0 | 0 | 0% | what it is |\n| supabase-js | 0 | 0 | 0% | likewise |"),
            &counts,
        )
        .expect("both rows are in the run");
        assert_eq!(recount(&once, &counts).expect("still parses"), once);
    }

    /// Both directions, because the failure this is here to stop is a
    /// row that outlives the suite it counted and goes on showing the
    /// last numbers anybody measured for it.
    #[test]
    fn a_page_and_a_run_that_disagree_about_the_suites_is_an_error() {
        let missing = recount(
            &page("| rest | 0 | 0 | 0% | what it is |"),
            &counted(&runs(), &[("supabase-js".to_string(), js())], &[]),
        )
        .expect_err("the run has a suite the page does not");
        assert!(missing.contains("supabase-js"), "{missing}");
        let extra = recount(
            &page("| rest | 0 | 0 | 0% | a |\n| gone | 0 | 0 | 0% | b |"),
            &counted(&runs(), &[], &[]),
        )
        .expect_err("the page has a row the run does not");
        assert!(extra.contains("gone"), "{extra}");
    }

    /// A page nobody marked up is refused rather than left alone, since
    /// the caller asked for this file to be rewritten and silence would
    /// read as it having been.
    #[test]
    fn a_page_with_no_markers_or_a_changed_table_is_refused() {
        let counts = counted(&runs(), &[], &[]);
        let bare = recount("just prose\n", &counts).expect_err("no markers");
        assert!(bare.contains(BEGIN), "{bare}");
        let half = recount(&format!("{BEGIN}\n\n{HEADER}\n{RULE}\n"), &counts)
            .expect_err("a begin and no end");
        assert!(half.contains(END), "{half}");
        let widened = page("| rest | 82 | 82 | 100% | what it is | and one more |");
        let refused = recount(&widened, &counts).expect_err("six cells");
        assert!(refused.contains("6 cells"), "{refused}");
    }

    /// The page this was written for, checked here rather than in the
    /// job that rewrites it.
    ///
    /// Nothing in this test can say whether the numbers on it are right,
    /// because only a run knows that and a run needs a stack. What it
    /// can say is that somebody editing the prose has not moved the
    /// markers or changed the columns, which would otherwise be found
    /// out by the scoreboard job of the merge that landed the edit, at
    /// which point the page is already on main saying its numbers came
    /// from a run.
    #[test]
    fn the_page_this_was_written_for_is_still_marked_up_for_it() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../docs/compatibility.md");
        let page = std::fs::read_to_string(path).expect("the page is in the repository");
        let table = page
            .split_once(BEGIN)
            .expect("the page carries the begin marker")
            .1
            .split_once(END)
            .expect("and the end marker")
            .0;
        assert_eq!(
            table.matches(HEADER).count(),
            1,
            "the columns between the markers are not the ones this writes"
        );
        assert!(table.contains(RULE));
    }
}
