-- The schema the generated types are checked against. It is not a real
-- application, it is one instance of every shape the generator has to
-- get right, which is why it reads like a list rather than a design.

create type public.mood as enum ('sad', 'ok', 'happy');
create type public.posted_at as (city text, at timestamptz);

create table public.users (
  id bigint generated always as identity primary key,
  handle text not null unique,
  email text,
  mood public.mood not null default 'ok',
  tags text[],
  profile jsonb not null default '{}'::jsonb,
  score numeric,
  created_at timestamptz not null default now()
);

create table public.posts (
  id uuid primary key default gen_random_uuid(),
  author_id bigint not null references public.users (id),
  title text not null,
  body text,
  where_when public.posted_at,
  published boolean not null default false
);

-- One to one, because the foreign key is unique.
create table public.post_stats (
  post_id uuid primary key references public.posts (id),
  views integer not null default 0
);

create view public.published_posts as
  select id, title, author_id from public.posts where published;

create materialized view public.post_counts as
  select author_id, count(*) as posts from public.posts group by author_id;

create function public.post_count(u public.users) returns bigint
  language sql stable as $$ select count(*) from public.posts p where p.author_id = u.id $$;

-- One unnamed argument of a table type is how a computed column is
-- spelled, so this one shows up on the row as well as under functions.
create function public.full_handle(public.users) returns text
  language sql stable as $$ select '@' || $1.handle $$;

-- One table in, another table out, which is a relationship the client
-- can follow rather than a plain call.
create function public.owner(p public.posts) returns public.users
  language sql stable as $$ select * from public.users where id = p.author_id $$;

create function public.tally(variadic ns integer[]) returns integer
  language sql immutable as $$ select coalesce(sum(n), 0)::integer from unnest(ns) as n $$;

create function public.top_posts(limit_to integer default 10)
  returns setof public.posts language sql stable as $$
    select * from public.posts order by id limit limit_to $$;

create function public.rename_user(user_id bigint, new_handle text) returns void
  language sql as $$ update public.users set handle = new_handle where id = user_id $$;

create function public.handles() returns table (id bigint, handle text)
  language sql stable as $$ select id, handle from public.users $$;

create function public.hottest() returns public.mood
  language sql immutable as $$ select 'happy'::public.mood $$;

-- A domain, and a column of a type nothing maps: both land on unknown
-- rather than on a guess.
create domain public.postcode as text;

create table public.oddities (
  id integer primary key,
  code public.postcode,
  moods public.mood[],
  when_open interval,
  raw bytea,
  at_time time,
  on_day date,
  small smallint not null,
  approximate real,
  spot point,
  flags bit(8)
);

-- A clean overload: different arity, so PostgREST can tell them apart
-- and the generated type is a union rather than an error.
create function public.search(q text) returns setof public.posts
  language sql stable as $$ select * from public.posts where title like q $$;
create function public.search(q text, limit_to integer) returns setof public.posts
  language sql stable as $$ select * from public.posts where title like q limit limit_to $$;

-- A single unnamed jsonb argument, which is the one unnamed shape
-- PostgREST will call.
create function public.echo(jsonb) returns jsonb language sql immutable as $$ select $1 $$;

-- Set returning without a relation behind it.
create function public.counters() returns setof integer
  language sql immutable as $$ select generate_series(1, 3) $$;

-- A view that cannot be written through.
create view public.mood_counts as
  select mood, count(*) as people from public.users group by mood;

-- A second schema, to see the ordering and the cross schema references.
create schema shop;
create type shop.currency as enum ('usd', 'eur');
create table shop.orders (
  id bigint generated by default as identity primary key,
  buyer_id bigint not null references public.users (id),
  paid_in shop.currency not null default 'usd',
  total numeric(10, 2) not null
);

-- Names that are not identifiers, and an enum long enough that both the
-- union and the constant array have to wrap.
create type public."order status" as enum (
  'awaiting_payment', 'payment_received', 'preparing_to_ship',
  'handed_to_carrier', 'delivered_to_customer', 'returned_by_customer'
);

create table public."gift cards" (
  id integer primary key,
  "full name" text not null,
  "2fa" boolean,
  status public."order status" not null default 'awaiting_payment'
);

-- A schema nobody asked to generate, so its types are reached from the
-- generated ones without being spelled out there. An enum still gets
-- its variants, since they are more use than unknown, and one long
-- enough to wrap gets them one to a line.
create schema hidden;
create type hidden.rank as enum ('bronze', 'silver', 'gold');
create type hidden.progress as enum (
  'awaiting_payment', 'payment_received', 'preparing_to_ship',
  'handed_to_carrier'
);
create type hidden.pair as (a integer, b integer);
create table hidden.secrets (id integer primary key, body text);

create table public.members (
  id integer generated always as identity primary key,
  tier hidden.rank not null,
  tiers hidden.rank[],
  progress hidden.progress,
  pair hidden.pair,
  secret_id integer references hidden.secrets (id)
);

-- Overloads PostgREST cannot choose between, once because one of them
-- takes an unnamed argument with a default and once because both spell
-- their argument the same. The generated type says so where a caller
-- will read it. The middle one is callable and is neither of the two
-- the message is about, so it is there to be stepped over. Its type
-- sorts before json, which is what puts it in the way.
create function public.pick() returns integer
  language sql immutable as $$ select 1 $$;
create function public.pick(a integer) returns integer
  language sql immutable as $$ select a $$;
create function public.pick(json default '{}'::json) returns json
  language sql immutable as $$ select $1 $$;

create function public.grow(x integer) returns integer
  language sql immutable as $$ select x + 1 $$;
create function public.grow(x text) returns text
  language sql immutable as $$ select x || '!' $$;

-- Two functions the catalog knows about and no client will ever call,
-- so neither of them is in the file.
create function public.touch_row() returns trigger
  language plpgsql as $$ begin return new; end $$;
create function public.watch_ddl() returns event_trigger
  language plpgsql as $$ begin end $$;

-- One unnamed row argument with nowhere to return to, which is a
-- function PostgREST has no way to call.
create function public.dead_end(hidden.secrets) returns text
  language sql stable as $$ select $1.body $$;

-- Set returning off one row, planned at one row and at many, which is
-- the difference between an object and an array on the client.
create function public.first_post(u public.users) returns setof public.posts
  language sql stable rows 1 as $$
    select * from public.posts where author_id = u.id order by id limit 1 $$;

-- One unnamed argument PostgREST cannot put a body in and cannot pass
-- by name, so the function is not in the file at all. A default does
-- not help, because a default only saves an argument PostgREST would
-- otherwise have had to fill in.
create function public.shout(integer) returns text
  language sql immutable as $$ select $1::text || '!' $$;
create function public.maybe(integer default 1) returns integer
  language sql immutable as $$ select $1 $$;

-- A row of no particular shape, which is as much as the client can be
-- told about it.
create function public.as_record(a integer) returns record
  language sql immutable as $$ select row(a, a) $$;

-- The same names in two schemas, which is the ordinary case in a
-- supabase project, where public.users sits next to auth.users. A type
-- named from public means the one in public.
create type shop.mood as enum ('cheap', 'dear');
create table shop.users (
  id bigint primary key,
  handle text not null,
  mood shop.mood not null default 'cheap'
);
create view shop.published_posts as
  select id, buyer_id from shop.orders where total > 0;
create function public.first_published() returns public.published_posts
  language sql stable as $$ select * from public.published_posts limit 1 $$;
create function public.title_of(v public.published_posts) returns text
  language sql stable as $$ select v.title $$;

-- A view naming the same column twice, which is two ways to follow one
-- foreign key and two relationships that differ only in where they
-- land.
create view public.author_ids as
  select id, id as also_id from public.users;
