#!/usr/bin/env bash
#
# Regenerate zou's auth schema from GoTrue's own migrations.
#
# GoTrue ships its schema as seventy migrations that have accumulated
# since 2020, several of which rename or drop what an earlier one
# created. Reading them and writing down the result by hand would be
# a transcription with seventy chances to be wrong, so instead this
# replays them against a scratch database and takes the shape that
# falls out.
#
# Two files come out of it:
#
#   crates/zou-server/src/auth-schema.sql
#     the consolidated ddl zou runs at bootstrap
#
#   crates/zou-server/tests/fixtures/gotrue-auth-fingerprint.txt
#     every column, constraint, index, enum and comment as one sorted
#     line each, which the auth schema test compares zou's own
#     bootstrap against
#
# Needs a running postgres with an empty database to replay into, and
# network access to fetch the pinned tag.
#
#   scripts/auth-schema-refresh.sh "host=127.0.0.1 port=5432 user=postgres dbname=scratch"
#
# The tag is pinned rather than tracking main, because a schema that
# moves under us is not a contract. Bump AUTH_TAG deliberately, rerun
# this, and read the diff.

set -euo pipefail

AUTH_TAG="${AUTH_TAG:-v2.194.0}"
DSN="${1:-}"
if [ -z "$DSN" ]; then
    echo "usage: $0 <dsn to an empty database>" >&2
    exit 2
fi

root="$(cd "$(dirname "$0")/.." && pwd)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

echo "fetching supabase/auth $AUTH_TAG migrations"
gh api "repos/supabase/auth/contents/migrations?ref=$AUTH_TAG" \
    --jq '.[] | select(.name|endswith(".up.sql")) | .name + " " + .download_url' \
    > "$work/list"

mkdir -p "$work/raw" "$work/sql"
while read -r name url; do
    curl -sSL "$url" -o "$work/raw/$name"
done < "$work/list"
echo "fetched $(ls "$work/raw" | wc -l | tr -d ' ') migrations"

# The migrations are go templates, and the only thing they interpolate
# is the schema name.
for f in "$work"/raw/*.up.sql; do
    sed -e 's/{{ *index \.Options "Namespace" *}}/auth/g' "$f" > "$work/sql/$(basename "$f")"
done

echo "replaying into $DSN"
psql "$DSN" -q -v ON_ERROR_STOP=1 -c "create schema if not exists auth" >/dev/null
# The migrations grant to these, so they have to exist first. On a
# real deployment they come from zou's own bootstrap.
for role in anon authenticated service_role supabase_auth_admin; do
    psql "$DSN" -q -c "do \$\$ begin
        if not exists (select 1 from pg_roles where rolname = '$role') then
            create role $role;
        end if;
    end \$\$" >/dev/null
done
for f in $(ls "$work"/sql/*.up.sql | sort); do
    psql "$DSN" -q -v ON_ERROR_STOP=1 -f "$f" >/dev/null
done

echo "recording the version rows"
# pop, the migration runner GoTrue uses, takes the version from the
# digits before the first underscore of the filename, so that is what
# lands in auth.schema_migrations and what a real GoTrue compares
# against when it decides whether it has work to do.
: > "$work/versions.sql"
for f in $(ls "$work"/raw/*.up.sql | sort); do
    v="$(basename "$f" .up.sql | sed -e 's/_.*$//')"
    echo "insert into auth.schema_migrations (version) values ('$v') on conflict do nothing;" \
        >> "$work/versions.sql"
done

echo "dumping"
pg_dump "$DSN" -n auth --schema-only --no-owner --no-privileges -f "$work/dump.sql"

out="$root/crates/zou-server/src/auth-schema.sql"
{
    cat <<EOF
-- The canonical auth schema, field compatible with GoTrue.
--
-- Generated by scripts/auth-schema-refresh.sh from supabase/auth
-- $AUTH_TAG by replaying its migrations and dumping the result. Do not
-- edit by hand: rerun the script against a new tag and read the diff.
--
-- Three things here are not verbatim GoTrue.
--
-- The four helper functions are CREATE OR REPLACE rather than CREATE,
-- because zou's own bootstrap defines them too and the two
-- definitions are the same text.
--
-- GoTrue's grants of select on the auth tables to postgres are not
-- here. They exist upstream because supabase_auth_admin owns the
-- tables and postgres is somebody else, while under zou the
-- connecting role creates them and therefore already owns them.
--
-- The version rows at the end are inserted so that a real GoTrue
-- pointed at this database considers itself up to date and does not
-- replay what is already here.
--
-- Applied once, on a database whose auth schema holds no tables yet.
-- zou never rewrites an auth schema it did not create; migrating an
-- older one is GoTrue's own job and is deliberately out of scope.

EOF
    # pg_dump writes a preamble of SET statements, a "-- Name: x; Type:
    # y" banner before every object, and a pair of \restrict directives
    # that only psql understands. None of it survives.
    sed -e '/^SET /d' \
        -e '/^SELECT pg_catalog\./d' \
        -e '/^\\restrict /d' \
        -e '/^\\unrestrict /d' \
        -e '/^-- Dumped/d' \
        -e '/^-- PostgreSQL database dump/d' \
        -e '/^-- Name: /d' \
        -e '/^--$/d' \
        "$work/dump.sql" \
        | sed -e 's/^CREATE SCHEMA auth;/CREATE SCHEMA IF NOT EXISTS auth;/' \
              -e 's/^CREATE TABLE /CREATE TABLE IF NOT EXISTS /' \
              -e 's/^CREATE INDEX /CREATE INDEX IF NOT EXISTS /' \
              -e 's/^CREATE UNIQUE INDEX /CREATE UNIQUE INDEX IF NOT EXISTS /' \
              -e 's/^CREATE FUNCTION /CREATE OR REPLACE FUNCTION /' \
        | cat -s
    cat "$work/versions.sql"
} > "$out"
echo "wrote $out ($(wc -l < "$out" | tr -d ' ') lines)"

fp="$root/crates/zou-server/tests/fixtures/gotrue-auth-fingerprint.txt"
mkdir -p "$(dirname "$fp")"
psql "$DSN" -qAt \
    -c "set zou.fingerprint_schema = 'auth'" \
    -f "$root/scripts/schema-fingerprint.sql" > "$fp"
echo "wrote $fp ($(wc -l < "$fp" | tr -d ' ') lines)"
