#!/usr/bin/env bash
# Write the homebrew formula for a release.
#
#   scripts/zou-bundle.sh --tar          # on each mac, into dist/
#   packaging/brew/formula.sh --version 0.2.0 > zou.rb
#
# The formula is generated rather than kept in the tree, because half of
# it is a pair of sha256 sums that only exist once the bundles do, and a
# checked in formula with last release's sums in it is a formula that
# installs the wrong thing.
#
# The sums are read from the checksum files the release job uploads next
# to the tarballs. A missing one becomes zeros, so the shape can be
# checked without a release to hand, and that is said on stderr rather
# than passed off as a formula somebody could use.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
version=""
dist="$(cd "$here/../.." && pwd)/dist"
repo="tamnd/zou"

while [ $# -gt 0 ]; do
  case "$1" in
    --version) version="$2"; shift 2 ;;
    --dist) dist="$2"; shift 2 ;;
    --repo) repo="$2"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [ -z "$version" ]; then
  echo "which version: packaging/brew/formula.sh --version 0.2.0" >&2
  exit 2
fi
version="${version#v}"

sha() {
  local file="$dist/zou-$1.tar.gz.sha256"
  if [ -f "$file" ]; then
    awk '{print $1}' "$file"
  else
    echo "no $file, writing zeros for $1" >&2
    printf '0%.0s' $(seq 64)
    echo
  fi
}

url() {
  echo "https://github.com/$repo/releases/download/v$version/zou-$1.tar.gz"
}

# Mac only, and on purpose. The mac bundle carries the libraries it
# needs that are not the operating system, so it stands on its own
# wherever it is unpacked. The linux one takes icu, readline and openssl
# from the distribution, which is a thing apt and dnf know about and
# homebrew on linux does not, so that platform has install.sh or the
# tarball rather than a formula that would install and then not run.
cat <<EOF
# Generated by packaging/brew/formula.sh in $repo, do not edit by hand.
class Zou < Formula
  desc "Supabase compatible backend that stores everything on object storage"
  homepage "https://github.com/$repo"
  version "$version"
  license "Apache-2.0"

  depends_on :macos

  on_arm do
    url "$(url darwin-arm64)"
    sha256 "$(sha darwin-arm64)"
  end

  on_intel do
    url "$(url darwin-x64)"
    sha256 "$(sha darwin-x64)"
  end

  def install
    # A release is the binary and the patched postgres together, and zou
    # finds the postmaster by looking beside itself, so the tree goes in
    # whole and only the command is linked into the prefix.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/zou"
  end

  test do
    assert_match "zou", shell_output("#{bin}/zou --version")
    # The half of the install that is not the binary. A zou without a
    # postmaster next to it cannot start a database, which is the whole
    # reason this formula ships a directory.
    assert_match "PostgreSQL", shell_output("#{libexec}/pg/bin/postgres --version")
  end
end
EOF
